# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 3.0

# Build documentation with Sphinx
sphinx:
    configuration: ./conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
    version: 3.8
