# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# --------------------------------- Required --------------------------------- #
# V2 or V1
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    
# ---------------------- Build documentation with Sphinx --------------------- #
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: conf.py


# ------- Optionally build your docs in additional formats such as PDF ------- #

formats: []


# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: requirements.txt